stages:
  - build

image: node:latest
build-job:
  stage: build
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: pnpm
    paths:
      - node_modules/
  script:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - dist
